### ISSUE TITLE
Add Milan to WIM website

### ISSUE THREAD

**Issue by ltmetz** [USGS-WiM/WIM-Main-Site#103]
Milan:

- [x] Draft a blurb for the WIM website & provide headshot (can check out [Team](https://wim.usgs.gov/team/#/) page for examples)
- [x] Then assign Mitch 

Mitch:

- [x] Add to website

**Comment by milanliu** [comment]
Milan has degrees in International Politics and Geography from Penn State University. Her interest in GIS and cartography brought her to WIM, where she works on projects involving data visualization and geonarrative design. Outside of work, Milan enjoys traveling and spending time outside. In her free time, you can usually find her on a run, reading a novel, or cooking a new recipe.  
![DSC06547](https://user-images.githubusercontent.com/81243372/113008674-da367780-913c-11eb-8f8d-dc381e4954e5.jpeg)
