### ISSUE TITLE
Add Daniel to WIM Website

### ISSUE THREAD

**Issue by ltmetz** [USGS-WiM/WIM-Main-Site#107]
Daniel,

- [x] Draft a blurb for the [WIM Website](https://wim.usgs.gov/team/#/) & provide headshot (can provide content in a comment)
- [x] Once complete, assign Mitch (mitchas)

Mitch,

- [x] Add Daniel to website

**Comment by chaqazarad** [comment]
![1605377041451](https://user-images.githubusercontent.com/85179214/120538544-a550d600-c3b4-11eb-99d2-b8bbf0fa8dd1.jpg)

Daniel has a B.S. in Public Affairs from Indiana University and is currently pursuing a Masters in Public Affairs from Indiana University.  Prior to joining USGS Daniel worked as a software designer and business analyst helping state and federal agencies solve challenges involving training, compliance, personnel management, organizational management, and more. Daniel loves the outdoors and has a lifelong goal of visiting all the national parks.
