### ISSUE TITLE
Add Lily to WIM Website

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/WIM-Main-Site#109]
Lily:
- [x] Draft a blurb for the WIM Website & provide headshot (can provide content in a comment)
- [x] Once complete, assign this ticket to Mitch (mitchas)

Mitch:
- [ ]  Add Lily to website

**Comment by lilyhoutman** [comment]
Lily is currently pursuing degrees in Cartography/GIS and Biological Anthropology at the University of Wisconsin-Madison. She is particularly interested in data journalism, science communication, and pedagogical teaching. She loves designing both static and web maps, and is always excited to explore the intersection of science and art that is inherent to cartography. In her free time, she enjoys running in the forest, reading fantasy novels, tending to her houseplants, and cooking vegetarian food.
![houtman_lily](https://user-images.githubusercontent.com/74278198/121021944-7e552400-c767-11eb-8540-edf01b1bfa3a.jpg)
