### ISSUE TITLE
Add Abby to WIM website

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#118]
Abby:

- [x]  Draft a blurb for the WIM Website & provide headshot (provide content in a comment in this issue)
- [x]  Once complete, assign this ticket to Mitch (mitchas)

Mitch:

 Add Abby to website

**Comment by BlakeDraper** [comment]
@Abigail770 bump on this task (unless you don't want to appear on the website).

**Comment by Abigail770** [comment]
Abby has a B.A. in Geography and M.S. in GIS and Web Map Programming from the University of Wisconsin-Madison.  Before pursuing her Master’s degree, she worked at a geospatial company specializing in LiDAR and pavement data collection.  While completing her Master’s program she held GIS positions at the Wisconsin State Cartographer’s Office and Wisconsin Emergency Management, creating both interactive and static maps.  In her free time, Abby enjoys running, exploring new trails in Wisconsin, painting, and volunteering with animals at the Humane Society.
![Abby_wim_photo](https://user-images.githubusercontent.com/54085652/137005561-f201bfa9-0d57-48d2-98f0-dcda9fd3e549.jpg)
