### ISSUE TITLE
Updates to Geonarratives Page

### ISSUE THREAD

**Issue by chaqazarad** [USGS-WiM/WIM-Main-Site#124]
- Add last line of text to the page description under Geonarratives main header
- Make sure Geonarrative Generator is linked in the text
- Add Milan to the bottom and make sure she is listed first
- Consider restyling the "Browse Geonarratives" section to something similar to pictured
- Consider using more tags
- If there are Geonarratives that WIM helped create consider tagging them and ordering them first

![image](https://user-images.githubusercontent.com/85179214/134695071-7259742c-1988-4990-ad86-9e6348dd5e9d.png)

**Comment by mitchas** [comment]
Closing - moved to issue #154 as we make larger changes to the site. Most of the Geonarratives page will be redone
