### ISSUE TITLE
Add Harper to Team

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#129]
@harper-wavra Comment on this issue with the following items:

- [x] draft blurb for the WIM website team page (click on photos to see examples of other blurbs) 
- [x] provide a headshot for the page
- [x] confirm Bismark, ND is the right place for your pin on the map

Then assign this issue to @mitch-wim

**Comment by harper-wavra** [comment]
Harper is a software developer for WIM. She received a B.S. in Computer Science from the University of North Dakota. She joined the USGS in 2015 and then joined the WIM team in 2021. Outside of work, Harper enjoys playing board games, sewing crafts, and hanging with her pets.
[Photo](https://user-images.githubusercontent.com/59063181/152034071-9c3dac74-4a01-4c2c-aae6-dac46d0273b2.jpg)
Bismarck, ND is the right place for the pin on the map.
