### ISSUE TITLE
Re-do build. Upgrade or remove Gulp

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/WIM-Main-Site#131]
The version of this gulp on this project depends on NPM ~11. It will not run unless you use nvm to use node v11 with it.
Upgrading gulp to v4 would fix the issue, but that would require rewriting all the gulp rules.

Maybe easier and better for future work to rebuild the project on Webpack?

**Comment by lprivette** [comment]
Either that or add instructions to the readme for using NVM and a specific node version.

**Comment by mitchas** [comment]
@lprivette Yeah it definitely wasn't hard getting it running with NVM, but gulp seems kind of dead, right? So I was thinking it may be worth it to switch if it's not a ton of work, especially since this project gets updated relatively consistently/frequently. 

Or maybe just wait for an eventual full site refresh with USWDS or something?

**Comment by lprivette** [comment]
Good points and I'd guess def worth switching-- might help with other existing projects too that use an old version of gulp. Not sure how soon a site refresh would be needed but I'm guess not anytime soon? Idk Hans probably has better input on that than I.

**Comment by mitchas** [comment]
Closing - will be done with parcel
