### ISSUE TITLE
Links to WIM Projects

### ISSUE THREAD

**Issue by kathymd** [USGS-WiM/WIM-Main-Site#134]
Include an easy and obvious way for people who visit WIM's home page access links to all of our projects. Maybe choose a few to highlight. Even if we only have a few that we highlight, I think it would still be great to have links (even if they're nothing fancy - just hyperlinks) to every single live/current web app we have publicly accessible. I'd love to know what all the apps are that WIM has - maybe someone else would too :) 
 
Project name, direct link to both the code and the final product. If we include 'Project Page', perhaps include it as a less-prominent link so it is not confused as *our* work. And also possibly rename it to 'Background' something else? As an outsider, I would think Project Page may very well be the home page for what we, WIM, created.

I really like what Vizlab did here! https://labs.waterdata.usgs.gov/visualizations/vizlab-home/index.html#/

**Comment by mitchas** [comment]
Closing - consolidating a few issues into one as we work on changes
