### ISSUE TITLE
Job Posting

### ISSUE THREAD

**Issue by kathymd** [USGS-WiM/WIM-Main-Site#135]
Would it be possible to put a job posting on our site? Doesn't need to be the home page, just some public link (wim.usgs.gov/jobs)? This would be helpful for advertising! It would look a little better than sending around pdfs. If it would be hard to do, don't worry about it. 

Here's a pdf with all the info
[Junior_Developer_WIM.pdf](https://github.com/USGS-WiM/WIM-Main-Site/files/8209682/Junior_Developer_WIM.pdf)

**Comment by HansVraga** [comment]
I don't like a solution where we'd need to update the site every time we post a job (or a job posting expires).

We could put something on the website directing visitors to watch usajobs.gov and the center social accounts for opportunities to join the team, though.

**Comment by mitchas** [comment]
Done - Creating a new issue to remove at the end
