### ISSUE TITLE
Update UMid Address in Footer

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/WIM-Main-Site#138]
It still lists the Middleton location, but should be the Madison location (1 Gifford Pinchot Dr, Madison, WI 53726) (or perhaps also St. Paul? 1992 Folwell Ave, St. Paul, MN 55108).

![image](https://user-images.githubusercontent.com/8713712/157544891-67488a1f-f623-49c8-b084-1df84e0195ee.png)

**Comment by mitchas** [comment]
Closing - combined with other small issues in progress
