### ISSUE TITLE
Main menu dissapears

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/WiM-Main-Site#14]
This is probably a non-issue because of what is needed to reproduce it, but anyway, steps to reproduce (Chrome Version 51.0.2704.103 m):

1. load site in full browser window
2. Reduce window size to mobile
3. click hamburger icon
4. choose "home, projects, or team"
5. increase browser size back to desktop, no more menu

**Comment by HansVraga** [comment]
Just to corroborate:
![image](https://cloud.githubusercontent.com/assets/12058013/17110766/1a050450-528e-11e6-9dbd-e9481b0d967d.png)
