### ISSUE TITLE
TIME SENSITIVE: Place WIM's job announcement onto WIM's website

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/WIM-Main-Site#143]
We are running into a lot of issues with Handshake being our primary job ad. It is set up to only work for schools that are on the official list, and it is showing as 'expired' if someone has an account associated with a non-list school. I think we should host the 'source of truth' job ad on our own website. Can be at something like `wim.usgs.gov/studentjob`. I can also do this myself with a hotpatch to S3 if you prefer. 

Job text in PDF below. 

[Junior_Developer_ContractPos_WIM.pdf](https://github.com/USGS-WiM/WIM-Main-Site/files/8235231/Junior_Developer_ContractPos_WIM.pdf)

Alternatively we could put this PDF directly in S3 for linking but I think a page would be better.

**Comment by jamvelk** [comment]
Hi @BlakeDraper , I saw this notification in my email. If you have a PDF of the job announcement, I can add it to the UMid website if you need a place to link to it. (Dru-paul)

**Comment by BlakeDraper** [comment]
@jamvelk would it be just a PDF link? or would you make a page for it?

**Comment by BlakeDraper** [comment]
@jamvelk the PDF is linked above, so you can grab it right there.

**Comment by kathymd** [comment]
@jamvelk Here is a PDF with formatting included
[Junior_Developer_WIM.pdf](https://github.com/USGS-WiM/WIM-Main-Site/files/8235211/Junior_Developer_WIM.pdf)

**Comment by kathymd** [comment]
Oops you can ignore that - I didn't see Blake swapped out the original PDF posted

**Comment by mitchas** [comment]
I can do this right now quick. So the PDF in the original comment is good to go? @BlakeDraper

**Comment by BlakeDraper** [comment]
@mitchas Yes.

**Comment by jamvelk** [comment]
the PDF is linked here, I can add the text into the page if you'd like instead: https://usgs.gov/media/files/junior-developer-studentrecent-grad-contract-position-web-informatics-and-mapping

**Comment by BlakeDraper** [comment]
@jamvelk Thanks this looks great  and I think it is fine since Mitch is also putting it on the WIM site. one small request though - could you swap that file out with the version at that top link now? I just fixed it so that there is not one line on its own page. Thanks!

**Comment by kathymd** [comment]
Mitch or Jamie - Would it be extra work to copy and paste the text on the website instead of uploading the PDF?

**Comment by jamvelk** [comment]
fixed that, and i'll put it on the socials, will link those here when done

**Comment by jamvelk** [comment]
no, i can definitely put it in the text if you'd prefer

**Comment by kathymd** [comment]
Awesome, thanks! I'll defer to Blake, but I do think that having the text directly on the website looks more professional and is more easily accessible

**Comment by BlakeDraper** [comment]
Just to close the circle on all this for all involved - Jamie is going to post the text and the PDF to a UMid page. She will then share that to UMid social media Mitch has also put the PDF up at the WIM site (on S3), but we have paused Mitch on making a page with the text since we can use the UMid page. Thanks to everyone for quick action!
@jamvelk @mitchas @kathymd  Have a great weekend everyone!

**Comment by jamvelk** [comment]
This is the text version of the announcement on its own page, on the right side you can see the PDF page in the "related documents" , it wouldn't let me link directly in the text, but you'll get to the launch page to the PDF itself https://usgs.gov/centers/upper-midwest-water-science-center/junior-developer-studentrecent-grad-contract-position

**Comment by BlakeDraper** [comment]
That works Jamie, thanks!

**Comment by kathymd** [comment]
This is exactly what we need! Thank you so much!

**Comment by jamvelk** [comment]
FB: https://www.facebook.com/photo?fbid=265446015764685&set=a.235657835410170
Insta: https://www.instagram.com/p/Ca-px1Qrfdz/
Twitter: https://twitter.com/USGS_UMid/status/1502395752315817990
