### ISSUE TITLE
Add Joe to the team

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#148]
@jfederer   Comment on this issue with the following items:

- [ ] draft blurb for the WIM website team page (click on photos to see examples of other blurbs) 
- [ ] provide a headshot for the page

Then assign this issue to @mitch-wim.

Joe joins the group in the Twin Cities for his map pin.

**Comment by HansVraga** [comment]
@jfederer bump! website edits are active - would be good to get you in there!

**Comment by jfederer** [comment]
Joe Federer is a full stack senior research developer and solutions architect at WIM. With multiple decades of experience leading an IT team at the USGS and graduating Suma Cum Laude from the Honors program at St. John's University with Departmental Distinction in Computer Science and a focus on Genetic Programming AI/ML techniques and High-Throughput Distributed Computing systems he founded and leads the Advanced Technology Group portfolio of projects. Currently, most of his time is engaged in AWS-based microservice serverless solutions, researching AI/ML within imagery-as-data solutions, workflow automation, and pioneering approaches for innovative web applications. Joe loves spending time with his family, playing hockey, and coaching/leading a wide array of activities within the community including soccer, hockey, Lego league, scouts, lacrosse, and other volunteering activities.


@milanliu  I'm told you do the final word-smithing.

**Comment by milanliu** [comment]
Looks pretty good to me! Here are the edits I'd suggest:

> Joe Federer is a full stack senior research developer and solutions architect at WIM. He graduated Summa Cum Laude from the Honors program at St. John’s University with Departmental Distinction in Computer Science and a focus on Genetic Programming AI/ML techniques and High-Throughput Distributed Computing Systems, and has multiple decades of experience leading an IT team at the USGS. Joe founded and leads the Advanced Technology Group portfolio of projects, and currently most of his time is engaged in AWS-based microservice serverless solutions, researching AI/ML within imagery-as-data solutions, workflow automation, and pioneering approaches for innovative web applications. Joe loves spending time with his family, playing hockey, and coaching/leading a wide array of activities within the community including soccer, hockey, Lego league, scouts, lacrosse, and other volunteering activities.

@mitchas - any length limitations/preferences for the site? I could cut down more if needed, but Joe does a lot of cool stuff. I'd go with the longer version to preserve Joe's original info if possible, but here's a slightly shorter version if you need it: 

> Joe Federer is a full stack senior research developer and solutions architect at WIM. He graduated from the Honors program at St. John’s University with distinction in Computer Science, and has multiple decades of experience leading an IT team at the USGS. Joe founded and leads the Advanced Technology Group portfolio of projects, and currently most of his time is engaged in AWS-based microservice serverless solutions, researching AI/ML within imagery-as-data solutions, workflow automation, and pioneering approaches for innovative web applications. Joe loves spending time with his family, playing hockey, and coaching/leading a wide array of activities within the community including soccer, hockey, Lego league, scouts, lacrosse, and other volunteering activities.

**Comment by HansVraga** [comment]
@jfederer also need a photo!

**Comment by jfederer** [comment]
I photoshopped myself in front of the stones (on top of Danny) from the summit: 

https://doimspp.sharepoint.com/:i:/r/sites/GS-UMidWIM/Shared%20Documents/Documents%20%26%20Resources/Hi-Res%20Team%20Headshots/WIM%20Team%20Photos/2022%20Summit%20Headshots/[Joe2022_1080.jpg](https://doimspp.sharepoint.com/:i:/r/sites/GS-UMidWIM/Shared%20Documents/Documents%20%26%20Resources/Hi-Res%20Team%20Headshots/WIM%20Team%20Photos/2022%20Summit%20Headshots/Joe2022_1080.jpg?csf=1&web=1&e=X9hkb7)?csf=1&web=1&e=X9hkb7

**Comment by jfederer** [comment]
assigned @mitch-wim  (I think - it would only let me assign @mitchas

**Comment by jfederer** [comment]
Complete?
