### ISSUE TITLE
Remediate Vulnerability: Medium jQuery and jQuery UI Components - BadRiver

### ISSUE THREAD

**Issue by ChadFanguy-usgs** [USGS-WiM/WIM-Main-Site#152]
jQuery at https://wim.usgs.gov/badriver/
1.9.0 to 3.4.1 are vulnerable
Recommended to move to 3.5.0.

jQuery UI (Autocomplete, Dialog, Tooltip) at https://wim.usgs.gov/badriver/newdataworth/
Recommended to move to 1.13.0.

Small low issue mentions a .DS_Store file in /badriver/ folder.

**Comment by mitchas** [comment]
Done - 

jQuery (and all JS) simply removed from /badriver/ - wasn't needed.

Updated jQuery and jQuery UI at /badriver/newdataworth/

Deleted the .DS_Store file
