### ISSUE TITLE
Remove Abby from WIM Website

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#153]
Abby has moved on from the USGS, please remove her from the Team page.

- [ ]  Remove Photo/blurb for Abby
- [ ]  Remove Abby from the  Madison, WI map pin

**Comment by mariobarbetta** [comment]
I'd be down to help with this one.  Is it up for grabs?

**Comment by HansVraga** [comment]
@mariobarbetta missed your offer! Thank you, but we've got this one as part of an effort we're planning in the near future.
