### ISSUE TITLE
Current Site Issues

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/WIM-Main-Site#154]
Consolidating issues related to current site into one issue. Some won't be relevant, but putting them here to keep in mind as we make changes.

General: 
#138 
> It still lists the Middleton location, but should be the Madison location (1 Gifford Pinchot Dr, Madison, WI 53726) (or perhaps also St. Paul? 1992 Folwell Ave, St. Paul, MN 55108).

Team Changes:

- [ ] Remove Abby
- [ ] Add Joe
- [ ] Add Andrew
- [ ] Jamie V to Alumni

Projects: 
#122 
> Several open links for projects are broken. Mitch thinks it has to do with an action not working. - Sparrow midwest, SIGL documentation, Merucrymapper, WetlandsProjects, probably more

#134 
> Include an easy and obvious way for people who visit WIM's home page access links to all of our projects. Maybe choose a few to highlight. Even if we only have a few that we highlight, I think it would still be great to have links (even if they're nothing fancy - just hyperlinks) to every single live/current web app we have publicly accessible. I'd love to know what all the apps are that WIM has - maybe someone else would too :)
> 
> Project name, direct link to both the code and the final product. If we include 'Project Page', perhaps include it as a less-prominent link so it is not confused as our work. And also possibly rename it to 'Background' something else? As an outsider, I would think Project Page may very well be the home page for what we, WIM, created.
> 
> I really like what Vizlab did here! https://labs.waterdata.usgs.gov/visualizations/vizlab-home/index.html#/

Geonarratives page:
#124 
> Add last line of text to the page description under Geonarratives main header
> Make sure Geonarrative Generator is linked in the text
> Add Milan to the bottom and make sure she is listed first
> Consider restyling the "Browse Geonarratives" section to something similar to pictured
> Consider using more tags
> If there are Geonarratives that WIM helped create consider tagging them and ordering them first

**Comment by BlakeDraper** [comment]
@mitchas need to also add Gene and Ethan

**Comment by lprivette** [comment]
need to also add Hannah now
