### ISSUE TITLE
Create team blurb for Hannah

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/WIM-Main-Site#158]
- [x] draft blurb for the WIM website [team page](https://wim.usgs.gov/team/) (click on photos to see examples of other blurbs)
- [x] provide a headshot for the page

Then assign this issue to @mitch-wim.

Hannah joins the group in the DC Area for their map pin.

**Comment by hrigdon98** [comment]
![IMG_4302](https://user-images.githubusercontent.com/72843561/188173218-1c34c343-a513-4403-8754-5b4ddd1fa195.jpg)

Hannah has a BS from in Geography from Middlebury College. Her interest in geospatial thinking and web development led her to WIM, where she is interested in the intersection of web mapping and science communication. Prior to joining WIM, she worked on a variety of environmentally focused GIS and remote sensing projects. Outside of work, Hannah enjoys board games, fiber arts and crafts, and getting to know her new home in Washington, DC.
