### ISSUE TITLE
Create Team blurb for Maggie

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/WIM-Main-Site#165]
In a comment for this issue:
- [ ] draft blurb for the WIM website [team page](https://wim.usgs.gov/team/) (click on photos to see examples of other blurbs)
- [ ] provide a headshot for the page

Then assign this issue to @mitch-wim.

Maggie joins the group in the Twin Cities for her map pin.

**Comment by maggiejaenicke** [comment]
Maggie earned her bachelor's degrees in geography and environmental studies from Macalester College in Saint Paul, Minnesota, where she gained skills in GIS and remote sensing. Before coming to WIM, Maggie completed two remote sensing research projects with NASA DEVELOP, one that focused on modeling suitable habitat for invasive grasses and one that focused on drought-related tree die-off events. Outside of work, she enjoys painting, biking, and learning about plants.

![Maggie](https://user-images.githubusercontent.com/91270407/192040511-bd67a389-ae90-41f2-8212-966e22acfd11.jpeg)
