### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jamvelk** [USGS-WiM/WiM-Main-Site#2]
1. the "learn more" tab for the Bad River Groundwater Model
2. the "open map" tab for FishVis
3. both the "open map" and "learn more" tab for the Iowa Streamflow Estimation tool.  Open map is broken and learn more cycles back to the wim page
4. the "open map" for Science in the Great Lakes
5. the "open map" for US EPA Bulletins Live Two BLT Mapper
6. the "open map" for US EPA San Francisco Bay Mapper, (also notice Francisco is misspelled)

**Comment by HansVraga** [comment]
In addition, the link to the Flood Event Viewer is incorrect - it should point to stn.wim.usgs.gov/fev
Science in the Great Lakes (SIGL) should point to http://sigl.wim.usgs.gov/sigl/
Flood Inundation Mapper (FIM): http://fim.wim.usgs.gov/FIM/

**Comment by HansVraga** [comment]
From the initial issues, only this one remains.
4. the "open map" for Science in the Great Lakes - should point to http://sigl.wim.usgs.gov/sigl/
