### ISSUE TITLE
Add Lauren to team page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WiM-Main-Site#24]
Photo - https://drive.google.com/open?id=0BygT1gkOzi3SM0ktak8wLVhnaWs
Lauren - Add Blurb to this issue & assign to Mitch.

**Comment by lprivette** [comment]
blurb: 

> Lauren is a software developer with WiM. She received her B.S in Geographic Science from James Madison University. While she enjoys work centered around GIS and cartography, her interests have expanded into the world of open source internet mapping. She currently resides in Northern Virginia and is working out of USGS HQ in Reston. Outside of work, Lauren enjoys snowboarding and ultimate frisbee.

Is this good? feel free to change anything.

**Comment by lprivette** [comment]
Fix is in Develop branch
