### ISSUE TITLE
Update my picture!

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WiM-Main-Site#3]
Update my photo to new, less pixelated photo taken by Erik.

**Comment by HansVraga** [comment]
![teamheadshots_rd2-hans](https://cloud.githubusercontent.com/assets/12058013/12815270/5f8bb94a-cb13-11e5-85b6-69e4bc84ace3.jpg)

**Comment by HansVraga** [comment]
Still not showing.

**Comment by marsmith** [comment]
HNOP

On Thu, Feb 4, 2016 at 7:46 AM, Hans Vraga <notifications@github.com> wrote:

> Still not showing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-WiM/WiM-Main-Site/issues/3#issuecomment-179813876>
> .
>



-- 

Martyn Smith
Cartographer
*marsmith@usgs.gov* <marsmith@usgs.gov>
518.285.5618
