### ISSUE TITLE
Show tags on Feature Projects repos

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#57]
![image](https://user-images.githubusercontent.com/12058013/56380371-05d62680-61e0-11e9-8ac3-920b32380923.png)

Include tags like they would be seen in the all projects list

**Comment by mitchas** [comment]
Those are just placeholders for now - they'll have the _exact_ same layout/design as the main list. I just wanted feedback to finalize the changes to the main list before I import it into the project pages.
