### ISSUE TITLE
Add Lorraine to WIM website

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#92]
Lorraine:
- [x]  draft blurb for the WIM website & provide headshot (go ahead an park both here), then assign @mitch-wim 

Mitch:
- [x] Add to Website

**Comment by ltmetz** [comment]
Blurb: Lorraine has a B.S. from Northland College in Geoscicence and Water Science and a graduate certificate in GIS from the University of Denver. She is currently working on her master's degree in GISc at the University of Denver. Lorraine joined the USGS in 2018 and then joined the WIM team in 2020. Outside of work, she enjoys spending time in the outdoors, listening to podcasts, reading, and hanging out with family and friends. 

![Lorraine_Headshot](https://user-images.githubusercontent.com/49204642/77466935-0ce6bb00-6dd9-11ea-9a6d-eca83f65673b.jpg)
